### ISSUE TITLE
Removed tag will not stay removed.

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#12]
I added "Story Maps" to an item's tags by typing it in. It became checked on the left side when I saved.  

I hit "Edit" again and clicked the "x" next to the tag on the right side. It removed from view, but when I hit "Save" it appeared again and also was checked on again.

**Comment by ChrisMahlke** [comment]
@jimherries  Working on this now...

**Comment by ChrisMahlke** [comment]
@jimherries Hey Jim, I pushed a fix, could you test?  If it breaks can you give me the repro so I can dig deeper?

**Comment by jimherries** [comment]
I just reproduced it, using the steps exactly as listed above.

**Comment by ChrisMahlke** [comment]
@jimherries @sbreyer Pushed.  FYI, the tags widget in the core API needs to be updated to support events (i.e.  detecting when new or existing tags are added/removed) to support the checkbox feature in this app.  Was discussed with Jeremy.

**Comment by jimherries** [comment]
Chris, can you collect all the recommendations/suggestions like this for Jeremy in a single document? Just something we have on hand, ready to show him any time.

Jim Herries | Product Engineer – Cartography
Esri<http://www.esri.com/> | 380 New York St | Redlands CA 92373 | USA
909.793.2853 extension 1-2489 | jherries@esri.com<mailto:jherries@esri.com> | @jherries<http://twitter.com/jherries> |  [btn_profile_greytxt_80x15] <http://www.linkedin.com/in/JimHerries>
909.202.2992 mobile

**Comment by ChrisMahlke** [comment]
I’m filing an issue on devtopia where he asked it to be documented.

**Comment by jimherries** [comment]
Ok, is that one issue containing everything we found in this project or?

Jim Herries | Product Engineer – Cartography
Esri<http://www.esri.com/> | 380 New York St | Redlands CA 92373 | USA
909.793.2853 extension 1-2489 | jherries@esri.com<mailto:jherries@esri.com> | @jherries<http://twitter.com/jherries> |  [btn_profile_greytxt_80x15] <http://www.linkedin.com/in/JimHerries>
909.202.2992 mobile

**Comment by ChrisMahlke** [comment]
I’d rather create issues in github (in the repo) instead of a document, so there is one place with the documented issues instead of different versions floating around.  The issues can be labelled something other than bugs or enhancements and can also be shared with Jeremy anytime.
