### ISSUE TITLE
Text edits not persisting

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#14]
For Description, Tags i have been making changes which are Saved, and persist during the session. But when I refresh the page and log in again, my changes are not shown.

To reproduce:
Edit a description. Save. 
Edit tags, adding one manually. Save.
Refresh the page and log in again.
Your changes are not reflected.

**Comment by jimherries** [comment]
User error. Closed.

**Comment by jimherries** [comment]
Reopening, with this modification: delete all of a description. It will appear to save that way when you hit Save, but refresh the page and log in again, and the original description is back.

**Comment by ChrisMahlke** [comment]
pushed
