### ISSUE TITLE
Change login page title

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#15]
On the login page, the title on top of the banner currently says:

 Living Atlas of the World: Nominate an app, web map or layer 

Please change to:

 Living Atlas of the World: Nominate an item

**Comment by jimherries** [comment]
Correction: please change to:

Please change to:

Living Atlas of the World: <new line>
Nominate an item

**Comment by ChrisMahlke** [comment]
@jimherries with or w/out the globe icon?

**Comment by jimherries** [comment]
nuke the globe
