### ISSUE TITLE
Set color of the 5 categories based on score status

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#16]
For the 5 colored buttons (Details, Use/Credits, Tags, etc) tie the color of the button to the score ratio for that section.  If the score ration >= 80% of available points, color the button blue. Otherwise, color the button red (the default).

**Comment by ChrisMahlke** [comment]
@jimherries Pushed

**Comment by ChrisMahlke** [comment]
@jimherries Need to update style (color, icon) of each category when clicking across.
