### ISSUE TITLE
Clicking across the 5 tabs alters the score

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#19]

**Comment by ChrisMahlke** [comment]
@jimherries Pushed.

**Comment by jimherries** [comment]
The score still varies as you tab across. Use curate88 account on the "2014 Alcohol" map. NOte the score when you first open. click on each tab once, to see the score changing.

**Comment by ChrisMahlke** [comment]
@jimherries Pushed update.
