### ISSUE TITLE
Add link to open item in AGOL

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#36]
The “Performance” tab does not allow edits.
o   It says I should share it but it does not give me the option to share from the app
o   It says I should add a pop-up but it doesn’t have an easy way to edit this from the app. Even an option to open the map elsewhere would possibly help

**Comment by jimherries** [comment]
add a button underneath the Nominate button that says "Open this item"

**Comment by ChrisMahlke** [comment]
Per Andrew's suggestion added icon link next to thumbnail
