### ISSUE TITLE
Score bar misleading

### ISSUE THREAD

**Issue by ChrisMahlke** [ChrisMahlke/nominate-2#38]
Users may not know the maximum score is 100.  The larger score (total score) is sometimes translated by the user to be the maximum score while the smaller "80" is translated by the user as their score.

**Comment by jimherries** [comment]
add "/100" behind the current score, in blue

**Comment by ChrisMahlke** [comment]
Added denominator
Made font smaller and the static "passing" scoe/label of 80 slightly opaque per @askinner13 suggetions
