### ISSUE TITLE
My profile thumbnail not uploading

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#4]
Error I get when uploading a valid jpg:

You are currently signed in as: 'curate88'. You do not have access to this resource: http://www.arcgis.com/sharing/rest/community/users/curate88/update

**Comment by ChrisMahlke** [comment]
@jimherries Pushed

**Comment by jimherries** [comment]
Still not working for me. Test with curate88 / curate88.  I still get 

You are currently signed in as: 'curate88'. You do not have access to this resource: http://www.arcgis.com/sharing/rest/community/users/curate88/update

Shouldn't it be trying to edit using my organizational URL at http://urbanobservatory.maps.arcgis.com/blahblahblah ?

**Comment by ChrisMahlke** [comment]
@jimherries What is the url you're testing?  The protocol should be https not http.
