### ISSUE TITLE
"Not Implemented Yet" for Help button

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#5]
If the user hits the Help button, give them a message "Not Implemented Yet"

**Comment by ChrisMahlke** [comment]
@jimherries Pushed HELP button placeholder...thoughts?

**Comment by jimherries** [comment]
My thoughts are that I don’t like that text.  Can we use "Not implemented yet” as requested?

Jim Herries | Product Engineer – Cartography
Esri<http://www.esri.com/> | 380 New York St | Redlands CA 92373 | USA
909.793.2853 extension 1-2489 | jherries@esri.com<mailto:jherries@esri.com> | @jherries<http://twitter.com/jherries> |  [btn_profile_greytxt_80x15] <http://www.linkedin.com/in/JimHerries>
909.202.2992 mobile
