### ISSUE TITLE
Nominate view - feature services and other item types return NaN score currently

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#56]

**Comment by jimherries** [comment]
A good map image service:
http://urbanobservatory.maps.arcgis.com/home/webmap/viewer.html?layers=11fadb936bdc4a729b4be23ad7870329

**Comment by jimherries** [comment]
For items which have no performance criteria (feature service, image service, etc) eliminate or gray out the Performance option; or, if the user clicks on Performance tab, pop up a message to say "Not available for this item type."

**Comment by ChrisMahlke** [comment]
@jimherries Hey Jim, I pushed a fix to nominate.
