### ISSUE TITLE
Verify that thumbnail rule evaluates file name "ago_downloaded.png"

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#62]
I noticed some items are using this "default" AGO thumbnail name, which we should be detecting and regarding as not a custom thumbnail:

ago_downloaded.png

**Comment by jimherries** [comment]
Look at 

EIA Shale Basins and Plays

on page 3 of the results

**Comment by ChrisMahlke** [comment]
@jimherries needs testing
