### ISSUE TITLE
Text alignment across the tabs

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#75]
There is a lack of consistency between the text orientation of the “Details” tab and the “Use/Credits” tab. In the “Details” section, the text appears in the same line as the blue text whereas in the “Use/Credits” section, the text is seen below the blue text. I would prefer to change the “Use/Credits” text format to match the “Details” section.

**Comment by ChrisMahlke** [comment]
@jimherries It's implemented per the mock up.  Create a new mockup and send it to me.
