### ISSUE TITLE
Consistent formatting for tabs' sections

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#82]
The text orientation of the “Details” tab and the “Use/Credits” tab differs. In the “Details” section, the text appears in the same line as the blue text, whereas in the “Use/Credits” section, the text is seen below the blue text. Can we change the “Use/Credits” text format to match the “Details” section, which looks so nice.

**Comment by jimherries** [comment]
see andy's mockup of what's desired in this attachment, sent via email

**Comment by ChrisMahlke** [comment]
Pushed to nominate
