### ISSUE TITLE
Updated tags to implement

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#83]
Deane shared these tags to use for all the major categories as well as the minor categories

Category	User Tag
Imagery	imagery
   Basemap Imagery	baseimagery
   Multispectral Imagery	multispectral
   Temporal Imagery	temporal
   Event Imagery	event_imagery
Basemaps	basemap
   Esri Basemaps	esri_basemap
   Partner Basemaps	partner_basemap
   User Basemaps	user_basemap
Historical Maps	historical
Demographics & Lifestyle	demographics
   Income	income
   Spending	spending
   Population	population
   Housing	housing
   Segmentation	segmentation
   Behaviors	behaviors
   Business	business
   Jobs	jobs
   At Risk	at risk
Landscape	landscape
   Climate	climate
   Weather	weather
   Ecology	ecology
   Species Biology	species
   Disturbance	disturbance
   Impact	impact
   Elevation	elevation
   Land Cover	landcover
   Natural Hazards	hazards
   Oceans	oceans
   Soils	soils
   Geology	geology
   Subsurface	subsurface
   Water	water
Earth Observations	earth observations
Urban Systems	urban
   3D Cities	3D
   Movement	movement
   Parcels	parcels
   People	people
   Planning	planning
   Public	public
   Work	work
Transportation	transportation
Boundaries and Places	boundaries
   Boundaries	boundaries
   Places	places
Story Maps	story map
Scenes	scenes

**Comment by ChrisMahlke** [comment]
@jimherries I don't know what you mean:

"Deane shared these tags to use for all the major categories as well as the minor categories"

Are those the labels that are displayed to the user?
Are they the actual tags that will be added in AGOL?  For instance, what exactly does this mean below?
User Basemaps use tag: user_basemap

**Comment by jimherries** [comment]
For Friday, you *could* merely swap the existing text with the required tags’ text, so that the UI shows:

+imagery (lowercase)
   +multispectral 

That’s a valid option, since we are, in fact, asking the user to properly tag the item, using the actual tag words.

**Comment by jimherries** [comment]
I'll meet with Deane and Sean to confirm what tag approach we should use (Living Atlas tags "as is" or Deane's list, or hybrid). I will know for sure by 2 pm

**Comment by ChrisMahlke** [comment]
@jimherries Hey Jim, I updated the tags to match Dean's requirement.  I'm unable to repro any issues you encountered.  If you find an issue would you be able to send me the steps the reproduce it, and I can debug it.  Leaving this issue open in case you find an issue.  Thanks.
