### ISSUE TITLE
Footer: update content as shown

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#88]
The entries below match the current page's layout:
Header1
Link1
Link2

Explore
ArcGIS.com Gallery (http://www.arcgis.com/home/gallery.html)
Living Atlas Web App (http://doc.arcgis.com/en/living-atlas)

Participate
How to Participate (http://blogs.esri.com/esri/arcgis/2014/07/22/contribute-to-the-living-atlas-of-the-world/)
Getting Started Video (http://video.esri.com/watch/3126/the-living-atlas)

Learn
Best Practices for Sharing (http://blogs.esri.com/esri/arcgis/2013/02/27/best-practices-for-community-web-maps-and-apps/)
Living Atlas Blogs (http://resources.arcgis.com/search/?do=search&collection=blogs&filter=0&lg=en&q=%22living+atlas%22&submit=)

ArcGIS.com  |  Help  |  Terms of Use  |  Privacy (links are listed in order below
http://www.esri.com/about-esri/contact
http://www.esri.com/legal/privacy
http://www.esri.com/legal
http://www.esri.com/site/sitemap.html

![screenshot 2015-03-25 15 07 51](https://cloud.githubusercontent.com/assets/5177430/6836589/c2fccc46-d300-11e4-81dc-d8b73b25e7f4.png)

**Comment by ChrisMahlke** [comment]
@jimherries I updated the footer b/c it was a simple fix (< couple minutes).  But I noticed the "Help" link points to privacy.  Is this correct or is there another link Help should point to?

**Comment by jimherries** [comment]
Corrected names and links are:

ArcGIS.com    |  Terms of Use    |  Privacy

http://www.arcgis.com
http://www.esri.com/legal
http://www.esri.com/legal/privacy
