### ISSUE TITLE
Can edit item Thumbnail outside of Edit session

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#9]
Just a note, in case you see this as a problem overall. You can change the thumbnail on an item without clicking the Edit button first. I don't see it as a UX issue.

**Comment by ChrisMahlke** [comment]
@jimherries Good catch!  That's a problem. Will fix it.

**Comment by ChrisMahlke** [comment]
@jimherries can you list the steps to repro the issue?

**Comment by ChrisMahlke** [comment]
@jimherries Nevermind, I got it.

**Comment by ChrisMahlke** [comment]
@jimherries pushed fix
