### ISSUE TITLE
Verify tag scoring - feature service

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/nominate-2#94]
To repro:
In curate88, see feature service item "AMASamples tags check"
I saved it with 5 tags total, two of which are added by checking one subtag in the checkable list.
I can only get 4/7 points currently.

**Comment by ChrisMahlke** [comment]
@jimherries Hey Jim, I just pushed a fix for this issue.  Was still checking the tag 'name' vs the 'tag'
Pushed fix to nominate-2
